package com.caseCRUD.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import jdk.jfr.DataAmount;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@DataAmount
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "tdl-db")
public class Lista {
	
    private String id;
    private String data;
    private String descricao;

    @DynamoDBHashKey(attributeName="ID")
    @DynamoDBAutoGeneratedKey
    public String getID() { return id;}
    public void setID(String id) {this.id = id;}
	
    @DynamoDBAttribute(attributeName="Data")
    public String getData() { return this.data; }
    public void setData(String data) { this.data = data; }
	
    @DynamoDBAttribute(attributeName="Descricao")
    public String getDescricao() { return this.descricao; }
    public void setDescricao(String descricao) { this.descricao = descricao; }
	
}
